AWSTemplateFormatVersion: "2010-09-09"
Description: A template for DynamoDB

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'guests'
      AttributeDefinitions:
        -
          AttributeName: 'email'
          AttributeType: 'S'
        -
          AttributeName: 'name'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: 'email'
          KeyType: 'HASH'

        -
          AttributeName: 'name'
          KeyType: 'RANGE'

      BillingMode: PAY_PER_REQUEST

